apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: elastic-stack
spec:
  ingressClassName: traefik 
  rules:
  - host: kibana.omc-task.dev
    http:
      paths:
      - backend:
          service:
            name: kibana-kb-http
            port:
              number: 5601
        pathType: ImplementationSpecific 
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true  