apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: elastic-stack
spec:
  count: 1
  version: 8.12.0
  config:
    pipeline.batch.size: 125
  elasticsearchRefs:
    - clusterName: eck
      name: elasticsearch
  services:
    - name: jenkins-tcp
      service:
        spec:
          ports:
            - name: tcp
              port: 9601
              targetPort: 9601
  pipelines:
    - pipeline.id: main
      pipeline.workers: 2
      config.string: |
        input { 
          tcp {
            port => 9601
            codec => json_lines
          }
        } 
        output {
          elasticsearch {
            hosts => [ "${ECK_ES_HOSTS}" ]
            user => "${ECK_ES_USER}"
            password => "${ECK_ES_PASSWORD}"
            cacert => "${ECK_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }