apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-public-to-kibana
  namespace: elastic-stack
spec:
  podSelector:
    matchLabels:
      app: kibana  # adjust if using different label
  ingress:
    - {}  # allow all sources
  policyTypes:
    - Ingress